name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Python Docker Image
        run: docker pull python:3.9-slim

      - name: Build Docker Container
        run: |
          docker build -t my-python-app .
      
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name my-python-container my-python-app

      - name: Verify Application
        run: curl -f http://localhost:5000 || exit 1

